version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  front_web:
    build:
      context: .
      dockerfile: infra/frontend/nginx/Dockerfile
    ports:
      - ${FRONTEND_WEB_PORT:-80}:80
    volumes:
      - ./frontend:/work/frontend

  backend_web:
    build:
      context: .
      dockerfile: infra/backend/nginx/Dockerfile
    ports:
      - ${BACKEND_WEB_PORT:-8080}:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend
    depends_on:
      - backend_app

  backend_app:
    build:
      context: .
      dockerfile: infra/backend/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}
      - CACHE_DRIVER=redis
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    depends_on:
      - db
      - cache

  db:
    build:
      context: .
      dockerfile: ./infra/mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel_local}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}

  cache:
    image: redis:latest
    ports:
      - ${CACHE_PORT:-6379}:6379
